name: R script workflow
on: [push]


    
jobs:
  run_r_script:
    runs-on: ubuntu-latest
    container:
      image: minhajuddin2510/rcode_files_update:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
       ref: test


    - name: Install system dependencies for R packages
      run: |
         apt-get install -y libudunits2-dev libproj-dev
  
    - name: Run R script
      env:
        GSHEET_SERVICE_ACCOUNT: ${{ secrets.GSHEET_SERVICE_ACCOUNT }}
      run: Rscript boerne-water-supply/rcode/use1_demand_data.R


    - name: Commit and push if changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add *.csv 
        git commit -m "Update data file" || echo "No changes to commit"
        git push
